export enum EventSeverity {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum ErrorCategory {
  VALIDATION = 'VALIDATION',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  CONTRACT = 'CONTRACT',
  DEPENDENCY = 'DEPENDENCY',
  TIMEOUT = 'TIMEOUT',
  PARITY = 'PARITY',
  FALLBACK = 'FALLBACK',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  TELEMETRY = 'TELEMETRY',
  UNKNOWN = 'UNKNOWN',
}
