// FINQZ PRO - Frontend permission mappings
// Bridges enterprise role permissions with the current frontend module menu keys.

import { ROLE_PERMISSIONS, type Role } from "../types";

const uniquePermissions = (permissions: readonly string[]): string[] => {
  return Array.from(new Set(permissions));
};

export const FRONTEND_ADMIN_PERMISSIONS = uniquePermissions([
  ...ROLE_PERMISSIONS.ROLE_ADMIN_SISTEMA,

  // Sidebar groups
  "CRM_VIEW",
  "OPERACOES_VIEW",
  "HUB_VIEW",
  "ADMIN_VIEW",

  // Dashboard
  "DASHBOARD_VIEW",

  // CRM
  "CLIENTES_VIEW",
  "CLIENTES_CREATE",
  "CLIENTES_EDIT",
  "CLIENTES_DELETE",
  "CLIENTES_EXPORT",
  "OPORTUNIDADES_VIEW",
  "OPORTUNIDADES_CREATE",
  "OPORTUNIDADES_EDIT",
  "OPORTUNIDADES_DELETE",
  "OPORTUNIDADES_MOVE_OPPORTUNITY",
  "OPORTUNIDADES_EXPORT",
  "SIMULADOR_VIEW",

  // Operacoes
  "PARCEIROS_VIEW",
  "PARCEIROS_CREATE",
  "PARCEIROS_EDIT",
  "PARCEIROS_DELETE",
  "PARCEIROS_RESET_PASSWORD",
  "PARCEIROS_EXPORT",
  "PRODUTOS_VIEW",
  "PRODUTOS_CREATE",
  "PRODUTOS_EDIT",
  "PRODUTOS_DELETE",
  "PRODUTOS_EXPORT",
  "ESTRUTURA_COMERCIAL_VIEW",
  "ESTRUTURA_COMERCIAL_CREATE",
  "ESTRUTURA_COMERCIAL_EDIT",
  "ESTRUTURA_COMERCIAL_DELETE",
  "ESTRUTURA_COMERCIAL_EXPORT",
  "TABELAS_COMERCIAIS_VIEW",
  "ROTEIROS_VIEW",
  "ROTEIROS_OPERACIONAIS_VIEW",
  "ROTEIROS_OPERACIONAIS_CREATE",
  "ROTEIROS_OPERACIONAIS_EDIT",
  "ROTEIROS_OPERACIONAIS_DELETE",
  "ROTEIROS_OPERACIONAIS_EXPORT",
  "FINANCEIRO_VIEW",
  "FINANCEIRO_VIEW_FINANCIAL",
  "FINANCEIRO_CREATE",
  "FINANCEIRO_EDIT",
  "FINANCEIRO_EXPORT",
  "CONTA_CORRENTE_VIEW",
  "CONTA_CORRENTE_VIEW_FINANCIAL",
  "CONTA_CORRENTE_EDIT",
  "RELATORIOS_VIEW",
  "RELATORIOS_VIEW_REPORTS",
  "RELATORIOS_EXPORT",

  // FINQZ Hub
  "AUDIENCIAS_VIEW",
  "AUDIENCIAS_CREATE",
  "AUDIENCIAS_EDIT",
  "AUDIENCIAS_DELETE",
  "AUDIENCIAS_IMPORT",
  "CAMPANHAS_VIEW",
  "CAMPANHAS_CREATE",
  "CAMPANHAS_EDIT",
  "CAMPANHAS_DELETE",
  "DISPAROS_VIEW",
  "WHATSAPP_VIEW",
  "CONVERSAS_VIEW",
  "SDR_IA_VIEW",
  "SDR_IA_USE",
  "HIGIENIZACAO_VIEW",
  "MAILING_VIEW",

  // Administracao
  "USUARIOS_VIEW",
  "USUARIOS_CREATE",
  "USUARIOS_EDIT",
  "USUARIOS_DELETE",
  "USUARIOS_RESET_PASSWORD",
  "PERMISSOES_VIEW",
  "AUDITORIA_VIEW",
  "AUDITORIA_EXPORT",
  "EVENTOS_VIEW",
  "CONFIGURACOES_VIEW",
  "CONFIGURACOES_CHANGE_SETTINGS",
  "GERAL_VIEW",
  "TAGS_VIEW",
  "PIPELINES_VIEW",
  "INTEGRACOES_VIEW",
  "AUTOMACOES_VIEW",
  "AUTOMACOES_CREATE",
  "AUTOMACOES_EDIT",
  "AUTOMACOES_DELETE",
  "NOTIFICACOES_VIEW",
  "SEGURANCA_VIEW",
  "BANCOS_VIEW",
]);

export const getFrontendPermissionsForRole = (role: Role): string[] => {
  const rolePermissions = ROLE_PERMISSIONS[role] ?? [];

  if (role !== "ROLE_ADMIN_SISTEMA") {
    return [...rolePermissions];
  }

  return uniquePermissions([...rolePermissions, ...FRONTEND_ADMIN_PERMISSIONS]);
};

export const mergeFrontendAdminPermissions = (permissions?: readonly string[]): string[] => {
  return uniquePermissions([...(permissions ?? []), ...FRONTEND_ADMIN_PERMISSIONS]);
};
