export enum MasterCatalogConsumer {
  OPORTUNIDADES = 'OPORTUNIDADES',
  ESTRUTURA_COMERCIAL = 'ESTRUTURA_COMERCIAL',
  COMMERCIAL_COVERAGE = 'COMMERCIAL_COVERAGE',
  SIMULATION_RUNTIME = 'SIMULATION_RUNTIME',
  LOAN_WITH_COLLATERAL = 'LOAN_WITH_COLLATERAL',
  LEGACY = 'LEGACY',
  MASTER_CATALOG = 'MASTER_CATALOG',
  SYSTEM = 'SYSTEM',
  UNKNOWN = 'UNKNOWN',
}

export enum MasterCatalogSourceType {
  FRONTEND_API = 'FRONTEND_API',
  HTTP_CONTROLLER = 'HTTP_CONTROLLER',
  RUNTIME = 'RUNTIME',
  SERVICE = 'SERVICE',
  REPOSITORY = 'REPOSITORY',
  SHADOW = 'SHADOW',
  EVIDENCE = 'EVIDENCE',
  CACHE = 'CACHE',
  TEST = 'TEST',
  UNKNOWN = 'UNKNOWN',
}

export enum MasterCatalogEventName {
  REQUEST_STARTED = 'MASTER_CATALOG_REQUEST_STARTED',
  REQUEST_FINISHED = 'MASTER_CATALOG_REQUEST_FINISHED',
  REQUEST_FAILED = 'MASTER_CATALOG_REQUEST_FAILED',
  PRIMARY_USED = 'MASTER_CATALOG_PRIMARY_USED',
  FALLBACK_USED = 'MASTER_CATALOG_FALLBACK_USED',
  SHADOW_STARTED = 'MASTER_CATALOG_SHADOW_STARTED',
  SHADOW_FINISHED = 'MASTER_CATALOG_SHADOW_FINISHED',
  SHADOW_DIVERGENCE = 'MASTER_CATALOG_SHADOW_DIVERGENCE',
  PARITY_RESULT = 'MASTER_CATALOG_PARITY_RESULT',
  CONSUMER_REGISTERED = 'MASTER_CATALOG_CONSUMER_REGISTERED',
  CACHE_HIT = 'MASTER_CATALOG_CACHE_HIT',
  CACHE_MISS = 'MASTER_CATALOG_CACHE_MISS',
}

export const MASTER_CATALOG_TELEMETRY_EVENT_VERSION = '1.0.0' as const;
export type MasterCatalogTelemetryEventVersion =
  typeof MASTER_CATALOG_TELEMETRY_EVENT_VERSION;
